### ISSUE TITLE
建议删除 bootcss.com 和 bootcdn.net

### ISSUE THREAD

**Issue by yk271** [felixonmars/dnsmasq-china-list#399]
cdn.bootcss.com 和 cdn.bootcdn.net 已经没有国内 CDN 节点了，建议删除或者只保留 www.bootcss.com

详见：
https://www.itdog.cn/ping/cdn.bootcss.com
https://www.itdog.cn/ping/cdn.bootcdn.net

**Comment by fernvenue** [comment]
Actually `bootcss.com` still has NS records in the white list:

```
~# dig @114.114.114.114 bootcss.com NS +short
ns2.alidns.com.
ns1.alidns.com.
```

But `bootcdn.net` seems can be remove:

```
~# dig @114.114.114.114 bootcdn.com NS +short
ns-cloud-c2.googledomains.com.
ns-cloud-c3.googledomains.com.
ns-cloud-c4.googledomains.com.
ns-cloud-c1.googledomains.com.
```

So maybe we can remove `bootcdn.net` but keep `bootcss.com`.

**Comment by felixonmars** [comment]
Actually even `bootcdn.net` is using dnspod according to gtld servers:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1006477/167994370-210fdcc2-bec0-4b4c-9bb1-e28117e60af4.png">

It appears you are testing the wrong domain :)

Since they resolves to similar cloudflare anycast IP across the globe, resolving it using China mainland DNS server should be harmless.

**Comment by fernvenue** [comment]
That's true, thanks for correcting me :)

And glad to know that anycast thing, I'll go learn more about this.
