### ISSUE TITLE
Remove jakting.com

### ISSUE THREAD

**Issue by TigerBeanst** [felixonmars/dnsmasq-china-list#401]
https://github.com/felixonmars/dnsmasq-china-list/commit/6ef903c5647a888079bd3ae863f5b1da5e28ddb6

For the purpose of protecting IP, I have used CloudFlare for it, resulting in poor access speed of its direct connection in China.

**Comment by felixonmars** [comment]
Removed. Thanks.

**Comment by TigerBeanst** [comment]
> Removed. Thanks.

I found that Cloudflare was not fast enough even through proxies... So I stopped using Cloudflare again, please help me add it back haha, I am a fool.

**Comment by fernvenue** [comment]
@TigerBeanst But you still use Cloudflare as your NS:

```
~# dig @114.114.114.114 jakting.com NS +short
rachel.ns.cloudflare.com.
aragorn.ns.cloudflare.com.
```

**Comment by fernvenue** [comment]
@TigerBeanst So we don't need to add it back, because when the domain's NS is in other region, even if the domain is resolved to an address in mainland China, we can still get the fastest resolution by DNS request from the other region in most cases.

Or...do you have any Geo based DNS records? Such as we can get different records from Mainland China and other places. If so, I think adding it back is a good idea. If not, we should keep it out of the list.

**Comment by fernvenue** [comment]
@TigerBeanst Actually, this list should **NOT** be used as a proxy or direct rule, this is just for DNS resolution, domains in this list may resolve to an IP address in or not in mainland China.
